import { useEffect, useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from "react";
import {
  Activity, Archive, BarChart3, CheckCircle2, ChevronDown, ChevronRight, CircleAlert, CircleDashed,
  Clock3, Code2, Database, ExternalLink, FileSearch, Filter, GitBranch, GitPullRequest, HardDrive,
  LayoutDashboard, ListFilter, LogIn, MoreHorizontal, Search, Server, Settings2, SlidersHorizontal,
  TerminalSquare, X,
} from "ynrlib/icons";
import { apiErrorMessage, apiErrorStatus, dashboardApi } from "./api";
import type { DashboardJob, DashboardLogLine, DashboardPayload, DashboardRun } from "./api";

type Section = "history" | "logs" | "runners" | "analytics" | "storage";
type RunStatus = "success" | "failed" | "running" | "queued";
const navItems: Array<{ id: Section; label: string; icon: typeof Activity }> = [
  { id: "history", label: "Run History", icon: LayoutDashboard },
  { id: "logs", label: "Logs", icon: FileSearch },
  { id: "runners", label: "Runners", icon: Server },
  { id: "analytics", label: "Analytics", icon: BarChart3 },
  { id: "storage", label: "Storage", icon: Archive },
];

function BlackBoxMark({ size = 32 }: { size?: number }) { return <img className="brand-mark" src="/black-box-mark.png" width={size} height={size} alt="Black Box" />; }
function UserAvatar({ login, avatarUrl, small = false }: { login: string; avatarUrl?: string | null; small?: boolean }) { return avatarUrl ? <img className={`avatar ${small ? "avatar-small" : ""}`} src={avatarUrl} alt="" /> : <span className={`avatar ${small ? "avatar-small" : ""}`}>{login.slice(0, 2).toUpperCase()}</span>; }
function runStatus(run: DashboardRun): RunStatus { if (run.status !== "completed") return run.status === "queued" ? "queued" : "running"; return run.conclusion === "success" ? "success" : "failed"; }
function StatusIcon({ status }: { status: RunStatus }) { return status === "success" ? <CheckCircle2 aria-hidden="true" className="status-icon success" /> : status === "failed" ? <CircleAlert aria-hidden="true" className="status-icon failed" /> : <CircleDashed aria-hidden="true" className={`status-icon ${status}`} />; }
function formatDuration(seconds: number | null | undefined): string { if (seconds === null || seconds === undefined) return "—"; if (seconds < 60) return `${seconds}s`; return `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`; }
function formatBytes(value: number | null | undefined): string { if (value === null || value === undefined) return "—"; const units = ["B", "GB", "TB"]; let amount = value; let index = 0; while (amount >= 1024 ** 3 && index < units.length - 1) { amount /= 1024 ** 3; index += 1; } return `${amount.toFixed(amount >= 100 ? 0 : 1)} ${units[index]}`; }
function formatAge(iso: string): string { const seconds = Math.max(0, Math.round((Date.now() - Date.parse(iso)) / 1000)); if (seconds < 60) return "just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86400)}d ago`; }
function displayName(login: string, name: string | null) { return name?.trim() || login; }

export function App() {
  const [section, setSection] = useState<Section>("history");
  const [query, setQuery] = useState("");
  const [showNotice, setShowNotice] = useState(true);
  const [range, setRange] = useState("1D");
  const [dashboard, setDashboard] = useState<DashboardPayload | null>(null);
  const [repositoryFilters, setRepositoryFilters] = useState<string[]>([]);
  const [workflowFilters, setWorkflowFilters] = useState<string[]>([]);
  const [eventFilters, setEventFilters] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<unknown>(null);
  const loadDashboard = () => { setLoading(true); setError(null); dashboardApi.getDashboard().then(setDashboard).catch(setError).finally(() => setLoading(false)); };
  useEffect(() => loadDashboard(), []);
  if (loading) return <StatusScreen title="Loading GitHub data" detail="Fetching repositories, workflow runs, and jobs from the connected account." />;
  if (!dashboard && apiErrorStatus(error) === 401) return <LoginScreen />;
  if (!dashboard) return <StatusScreen title="Black Box could not load GitHub data" detail={apiErrorMessage(error)} action={<button className="button button-light" onClick={loadDashboard}>Retry</button>} />;
  const title = navItems.find((item) => item.id === section)?.label ?? "Run History";
  const filteredRuns = dashboard.runs.filter((run) => {
    const needle = query.trim().toLowerCase();
    const matchesText = !needle || [run.title, run.name, run.repo, run.branch, run.event, run.status, run.conclusion ?? ""].some((value) => value.toLowerCase().includes(needle));
    return matchesText && (!repositoryFilters.length || repositoryFilters.includes(run.repo)) && (!workflowFilters.length || workflowFilters.includes(run.name)) && (!eventFilters.length || eventFilters.includes(run.event));
  });
  const toggleFilter = (setter: Dispatch<SetStateAction<string[]>>, value: string) => setter((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]);
  const warnings = dashboard.warnings ?? [];
  return <div className="app-shell">
    <aside className="icon-rail" aria-label="Primary navigation"><button className="rail-brand" aria-label="Black Box home" onClick={() => setSection("history")}><BlackBoxMark size={36} /></button><div className="rail-actions">{navItems.slice(0, 3).map(({ id, label, icon: Icon }) => <button key={id} className={`rail-button ${section === id ? "is-active" : ""}`} aria-label={label} aria-pressed={section === id} onClick={() => setSection(id)}><Icon size={18} strokeWidth={1.8} aria-hidden="true" /></button>)}</div><div className="rail-spacer" /><button className="rail-button" aria-label="Settings" onClick={() => setSection("storage")}><Settings2 size={18} strokeWidth={1.8} aria-hidden="true" /></button><span className="online-dot" title="GitHub data connected" /></aside>
    <aside className="context-sidebar"><div className="product-heading"><BlackBoxMark size={26} /><div><strong>Black Box</strong><span>Personal CI control plane</span></div><button className="icon-button" aria-label="Refresh dashboard" onClick={loadDashboard}><Search size={17} strokeWidth={1.8} aria-hidden="true" /></button></div><nav className="side-nav" aria-label="Dashboard sections">{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={`side-nav-item ${section === id ? "is-active" : ""}`} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)}><Icon size={16} strokeWidth={1.8} aria-hidden="true" /><span>{label}</span>{(id === "history" || id === "analytics" || id === "storage") && <ChevronRight size={14} aria-hidden="true" />}</button>)}</nav>{section === "logs" ? <LogFilters jobs={dashboard.jobs} /> : <HistoryFilters repositories={dashboard.repositories.map((repo) => repo.fullName)} runs={dashboard.runs} selectedRepositories={repositoryFilters} selectedWorkflows={workflowFilters} selectedEvents={eventFilters} onRepositoryToggle={(value) => toggleFilter(setRepositoryFilters, value)} onWorkflowToggle={(value) => toggleFilter(setWorkflowFilters, value)} onEventToggle={(value) => toggleFilter(setEventFilters, value)} />}<div className="sidebar-user"><UserAvatar login={dashboard.user.login} avatarUrl={dashboard.user.avatarUrl} /><div className="user-copy"><strong>{displayName(dashboard.user.login, dashboard.user.name)}</strong><span>GitHub connected</span></div><ChevronDown size={15} aria-hidden="true" /></div></aside>
    <main className="main-content"><header className="topbar"><div className="title-block"><span className="eyebrow"><span className="eyebrow-mark" /> Black Box / GitHub Actions</span><h1>{title}</h1></div><div className="topbar-actions"><div className="range-control" aria-label="Time range">{["1h", "4h", "12h", "1D", "2D", "5D"].map((item) => <button key={item} className={range === item ? "is-selected" : ""} onClick={() => setRange(item)}>{item}</button>)}</div><button className="date-control"><Clock3 size={14} aria-hidden="true" /> Updated {formatAge(dashboard.fetchedAt)}</button></div></header><div className="content-scroll">{showNotice && <div className="migration-notice"><div className="notice-symbol"><Code2 size={17} strokeWidth={1.8} aria-hidden="true" /></div><div><strong>GitHub data is live</strong><span>{dashboard.repositories.length} repositories · {dashboard.runs.length} recent workflow runs loaded.</span></div><button aria-label="Dismiss connection notice" onClick={() => setShowNotice(false)}><X size={16} aria-hidden="true" /></button></div>}{warnings.map((warning, index) => <div className="data-warning" key={`${warning.code}-${warning.repository ?? "all"}-${index}`}><CircleAlert size={15} aria-hidden="true" /><span>{warning.message}{warning.repository ? ` ${warning.repository}` : ""}</span></div>)}{section === "history" && <RunHistoryView query={query} setQuery={setQuery} runs={filteredRuns} allRuns={dashboard.runs} />}{section === "logs" && <LogsView jobs={dashboard.jobs} />}{section === "runners" && <RunnersView host={dashboard.host} />}{section === "analytics" && <AnalyticsView runs={dashboard.runs} />}{section === "storage" && <StorageView host={dashboard.host} />}</div></main>
  </div>;
}

function StatusScreen({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <main className="status-screen"><BlackBoxMark size={54} /><span className="eyebrow">Black Box / GitHub Actions</span><h1>{title}</h1><p>{detail}</p>{action}</main>; }
function LoginScreen() { const loginUrl = `${dashboardApi.baseUrl}/auth/github` || "/auth/github"; return <main className="status-screen"><BlackBoxMark size={54} /><span className="eyebrow">Black Box / GitHub Actions</span><h1>Connect GitHub to inspect your CI</h1><p>Black Box reads repositories, workflow runs, jobs, and logs with a server-side GitHub session. No access token is sent to this browser.</p><a className="button button-light" href={loginUrl}><LogIn size={15} aria-hidden="true" /> Continue with GitHub</a></main>; }
function HistoryFilters({ repositories, runs, selectedRepositories, selectedWorkflows, selectedEvents, onRepositoryToggle, onWorkflowToggle, onEventToggle }: { repositories: string[]; runs: DashboardRun[]; selectedRepositories: string[]; selectedWorkflows: string[]; selectedEvents: string[]; onRepositoryToggle: (value: string) => void; onWorkflowToggle: (value: string) => void; onEventToggle: (value: string) => void }) { return <div className="filter-groups"><FilterGroup title="Repositories" items={repositories.slice(0, 6)} selected={selectedRepositories} onToggle={onRepositoryToggle} /><FilterGroup title="Workflows" items={[...new Set(runs.map((run) => run.name))].slice(0, 8)} selected={selectedWorkflows} onToggle={onWorkflowToggle} /><FilterGroup title="Sources" items={[...new Set(runs.map((run) => run.event))]} selected={selectedEvents} onToggle={onEventToggle} /></div>; }
function LogFilters({ jobs }: { jobs: DashboardJob[] }) { return <div className="filter-groups"><FilterGroup title="Jobs" items={[...new Set(jobs.map((job) => job.name))].slice(0, 8)} /><FilterGroup title="Outcomes" items={["Success", "Failure", "Queued"]} /><FilterGroup title="Repositories" items={[...new Set(jobs.map((job) => job.repo))].slice(0, 6)} /></div>; }
function FilterGroup({ title, items, selected, onToggle }: { title: string; items: string[]; selected?: string[]; onToggle?: (value: string) => void }) { return <section className="filter-group"><div className="filter-heading"><span>{title}</span><ChevronDown size={14} aria-hidden="true" /></div><label className="filter-search"><Search size={14} aria-hidden="true" /><input placeholder={`Filter ${title.toLowerCase()}...`} /></label>{items.length ? items.map((item) => <label className="check-row" key={item}><input type="checkbox" checked={selected?.includes(item) ?? false} onChange={() => onToggle?.(item)} /><span className="fake-check" /><span>{item}</span></label>) : <span className="sidebar-empty">No data loaded</span>}</section>; }

function RunHistoryView({ query, setQuery, runs, allRuns }: { query: string; setQuery: (value: string) => void; runs: DashboardRun[]; allRuns: DashboardRun[] }) { return <><section className="intro-row"><div><span className="eyebrow">Signal over noise</span><h2>Find the run you’re looking for</h2><p>These are live workflow runs from GitHub. Filter by repository, workflow, branch, event, or result and open the original run when you need the full trace.</p></div><div className="intro-actions"><button className="button button-light" onClick={() => setQuery("")}><SlidersHorizontal size={15} aria-hidden="true" /> Clear search</button><a className="button button-quiet" href="https://docs.github.com/en/actions" target="_blank" rel="noreferrer"><ExternalLink size={15} aria-hidden="true" /> GitHub Actions docs</a></div></section><RunDistribution runs={allRuns} /><section className="work-area"><div className="inline-filters"><div className="section-caption"><Filter size={14} aria-hidden="true" /> Active search</div>{query && <button className="filter-chip" onClick={() => setQuery("")}>{query}<X size={12} aria-hidden="true" /></button>}<span className="sidebar-empty">{query ? "Matching live runs" : "No filters"}</span></div><div className="results-panel"><div className="results-header"><div><span className="eyebrow">Runs</span><strong>{runs.length} shown · {allRuns.length} loaded</strong></div><label className="table-search"><Search size={15} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search runs" /></label><button className="icon-button" aria-label="More run options"><MoreHorizontal size={18} aria-hidden="true" /></button></div><div className="run-list">{runs.length ? runs.map((run) => <RunRow key={`${run.id}-${run.attempt}`} run={run} />) : <EmptyState title="No matching runs" detail="Try a repository, workflow, branch, or status." />}</div></div></section></>; }
function RunDistribution({ runs }: { runs: DashboardRun[] }) { const recent = runs.slice(0, 24).reverse(); const points = recent.length ? recent.map((run, index) => `${index * (1000 / Math.max(recent.length - 1, 1))},${runStatus(run) === "failed" ? 75 : runStatus(run) === "success" ? 34 : 52}`).join(" ") : "0,90 1000,90"; const success = runs.filter((run) => runStatus(run) === "success").length; const failed = runs.filter((run) => runStatus(run) === "failed").length; return <section className="chart-panel"><div className="section-caption"><Activity size={14} aria-hidden="true" /> Workflow run distribution <span>last {runs.length} loaded runs</span></div><svg className="line-chart" viewBox="0 0 1000 110" preserveAspectRatio="none" aria-label="Workflow run distribution chart"><polyline points={points} /></svg><div className="chart-legend"><span><i className="legend-dot success" /> success {success}</span><span><i className="legend-dot failed" /> failed {failed}</span><span>source · GitHub Actions API</span></div></section>; }
function RunRow({ run }: { run: DashboardRun }) { const status = runStatus(run); return <article className="run-row"><StatusIcon status={status} /><div className="run-main"><strong>{run.title || run.name}</strong><span><UserAvatar login={String(run.runNumber)} small />{run.name}<em>·</em><b>{run.repo}</b><em>·</em><GitBranch size={12} aria-hidden="true" />{run.branch}<em>·</em>{run.event}</span></div><div className="run-meta"><span>{formatAge(run.updatedAt)}</span><span>{formatDuration(run.durationSeconds)}</span><i className={`duration-bar ${status}`} /></div><a className={`run-state ${status}`} href={run.htmlUrl} target="_blank" rel="noreferrer">{status}<ExternalLink size={12} aria-hidden="true" /></a></article>; }

function LogsView({ jobs }: { jobs: DashboardJob[] }) {
  const [selectedJobId, setSelectedJobId] = useState<number | null>(jobs[0]?.id ?? null); const [query, setQuery] = useState(""); const [lines, setLines] = useState<DashboardLogLine[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const selectedJob = jobs.find((job) => job.id === selectedJobId) ?? null;
  useEffect(() => { if (!selectedJob) { setLines([]); return; } setLoading(true); setError(null); dashboardApi.getJobLogs(selectedJob).then(setLines).catch((reason) => setError(apiErrorMessage(reason))).finally(() => setLoading(false)); }, [selectedJobId, selectedJob]);
  const filtered = lines.filter((line) => line.message.toLowerCase().includes(query.toLowerCase()));
  return <><section className="intro-row"><div><span className="eyebrow">Trace every signal</span><h2>Debug flaky tests and bugs</h2><p>Job logs come from GitHub’s log endpoint and load only for the selected job. Black Box truncates a single response at 2 MiB.</p></div><div className="intro-actions"><button className="button button-light" onClick={() => selectedJob && setSelectedJobId(selectedJob.id)}><FileSearch size={15} aria-hidden="true" /> Reload log</button><button className="button button-quiet">Retention <ChevronRight size={14} aria-hidden="true" /></button></div></section><LogVolume lines={lines} loading={loading} /><section className="logs-panel"><div className="results-header"><div><span className="eyebrow">Job log</span><strong>{jobs.length} jobs available</strong></div><select className="job-select" aria-label="Select job log" value={selectedJobId ?? ""} onChange={(event) => setSelectedJobId(event.target.value ? Number(event.target.value) : null)}><option value="">Choose a job</option>{jobs.map((job) => <option key={job.id} value={job.id}>{job.repo} · {job.name}</option>)}</select><label className="table-search wide"><Search size={15} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search this log..." /></label><button className="button button-quiet"><ListFilter size={15} aria-hidden="true" /> Filters</button></div>{error ? <EmptyState title="Log could not be loaded" detail={error} /> : !selectedJob ? <EmptyState title="Choose a job to inspect its log" detail="Black Box fetches a log only after you select a job." /> : <div className="log-table"><div className="log-header"><span>Level</span><span>Job ID</span><span>Job name</span><span>Message</span></div>{filtered.length ? filtered.map((line, index) => <div className="log-row" key={`${selectedJob.id}-${index}`}><span className={`log-level ${line.level.toLowerCase()}`}>{line.level}</span><span className="mono">{selectedJob.id}</span><span className="job-name">{selectedJob.name}</span><span className="log-message">{line.message}</span></div>) : <EmptyState title={loading ? "Loading job log" : "No matching log lines"} detail={loading ? "Fetching the selected job output from GitHub." : "Try a different search term."} />}</div>}</section></>; }
function LogVolume({ lines, loading }: { lines: DashboardLogLine[]; loading: boolean }) { const buckets = Array.from({ length: 22 }, (_, index) => lines.slice(Math.floor(index * lines.length / 22), Math.floor((index + 1) * lines.length / 22))); const max = Math.max(1, ...buckets.map((bucket) => bucket.length)); return <section className="chart-panel log-volume"><div className="section-caption"><Activity size={14} aria-hidden="true" /> Selected log volume <span>{loading ? "loading" : `${lines.length.toLocaleString()} lines loaded`}</span></div><div className="bar-chart" aria-label="Selected job log volume chart">{buckets.map((bucket, index) => { const level = bucket.some((line) => line.level === "ERROR") ? "error" : bucket.some((line) => line.level === "WARN") ? "warn" : ""; return <i className={`volume-bar ${level}`} style={{ height: `${bucket.length ? Math.max(5, bucket.length / max * 100) : 0}%` }} key={index} />; })}</div><div className="chart-legend"><span><i className="legend-dot info" /> source · GitHub job logs</span><span><i className="legend-dot warn" /> warning/error buckets use the loaded lines</span></div></section>; }

function RunnersView({ host }: { host: DashboardPayload["host"] }) { const online = host?.status === "online"; return <section className="overview-page"><div className="page-heading"><div><span className="eyebrow">Execution capacity</span><h2>Runners</h2><p>These values come from the signed WSL host telemetry agent. A stale host is shown as stale instead of being treated as ready.</p></div><button className="button button-quiet" disabled><Settings2 size={15} aria-hidden="true" /> Agent setup needed</button></div><div className="metric-grid"><Metric label="Host status" value={host ? (online ? "Online" : "Stale") : "Not reported"} detail={host ? `${host.hostname} · ${host.ageSeconds}s ago` : "WSL telemetry endpoint is not connected"} icon={<Server size={18} />} tone={online ? "success" : undefined} /><Metric label="CPU" value={host ? `${host.cpuPercent.toFixed(1)}%` : "—"} detail={host ? "host-wide sample" : "Awaiting host agent"} icon={<Activity size={18} />} /><Metric label="Memory" value={host ? `${formatBytes(host.memoryUsedBytes)} / ${formatBytes(host.memoryTotalBytes)}` : "—"} detail={host?.wslMemoryLimitBytes ? `WSL limit ${formatBytes(host.wslMemoryLimitBytes)}` : "Awaiting host agent"} icon={<Database size={18} />} /><Metric label="Storage" value={host ? formatBytes(host.diskFreeBytes) : "—"} detail={host ? `free of ${formatBytes(host.diskTotalBytes)}` : "Awaiting host agent"} icon={<HardDrive size={18} />} /></div><div className="runner-card"><div className="runner-card-heading"><div><span className="eyebrow">GitHub runner telemetry</span><h3>{host?.runnerName ?? "Not yet connected"}</h3></div><span className="status-badge"><span style={{ background: online ? "var(--green)" : "var(--yellow)" }} /> {host ? (online ? "Ready" : "Stale") : "Awaiting agent"}</span></div><div className="runner-details"><span><GitBranch size={15} /> self-hosted · Linux · X64</span><span><TerminalSquare size={15} /> WSL2 Ubuntu</span><span><Database size={15} /> Docker {host ? (host.dockerReady ? "ready" : "not ready") : "unknown"}</span></div><div className="runner-footer"><span>{host ? `Last telemetry ${host.ageSeconds}s ago` : "Real hardware values are never estimated"}</span><button className="button button-quiet" disabled>Open host details <ChevronRight size={14} /></button></div></div></section>; }
function AnalyticsView({ runs }: { runs: DashboardRun[] }) { const successes = runs.filter((run) => runStatus(run) === "success").length; const failures = runs.filter((run) => runStatus(run) === "failed").length; const durations = runs.map((run) => run.durationSeconds).filter((value) => value > 0).sort((a, b) => a - b); const median = durations.length ? durations[Math.floor(durations.length / 2)] : null; const failedRuns = runs.filter((run) => runStatus(run) === "failed").slice(0, 4); return <section className="overview-page"><div className="page-heading"><div><span className="eyebrow">Measure the work</span><h2>Analytics</h2><p>These metrics come from live GitHub workflow runs. Host cost, cache hits, and flaky-test rates need Black Box agent data.</p></div><button className="button button-quiet" disabled><GitPullRequest size={15} aria-hidden="true" /> Compare periods later</button></div><div className="metric-grid"><Metric label="Loaded runs" value={String(runs.length)} detail={`${successes} successful · ${failures} failed`} icon={<GitPullRequest size={18} />} /><Metric label="Success rate" value={runs.length ? `${Math.round((successes / runs.length) * 100)}%` : "—"} detail="based on loaded runs" icon={<CheckCircle2 size={18} />} tone="success" /><Metric label="Median runtime" value={formatDuration(median)} detail="from GitHub run timestamps" icon={<Clock3 size={18} />} /><Metric label="Cache hit rate" value="—" detail="requires Black Box cache events" icon={<Database size={18} />} /></div><div className="insight-list">{failedRuns.length ? failedRuns.map((run) => <Insight key={run.id} title={`${run.title || run.name} failed`} detail={`${run.repo} · ${run.branch} · ${formatAge(run.updatedAt)}`} status="Open run" href={run.htmlUrl} />) : <EmptyState title="No failed runs in the loaded window" detail="Black Box will show evidence-backed failure patterns when the API returns them." />}</div></section>; }
function StorageView({ host }: { host: DashboardPayload["host"] }) { const used = host ? Math.max(0, Math.min(100, 100 - (host.diskFreeBytes / host.diskTotalBytes) * 100)) : 0; return <section className="overview-page"><div className="page-heading"><div><span className="eyebrow">Local state</span><h2>Storage</h2><p>Host disk telemetry is real. Per-cache inventory remains unavailable until the agent reports BuildKit and package-store ownership.</p></div><button className="button button-quiet" disabled><SlidersHorizontal size={15} aria-hidden="true" /> Policy later</button></div><div className="storage-layout"><div className="storage-meter"><div className={`meter-ring ${host ? "" : "unavailable-ring"}`} style={host ? { background: `conic-gradient(var(--cyan) 0 ${used}%,#253236 ${used}% 100%)` } : undefined}><strong>{host ? `${Math.round(used)}%` : "—"}</strong><span>{host ? "used" : "not reported"}</span></div><span>{host ? `${formatBytes(host.diskFreeBytes)} available` : "Host storage telemetry is unavailable"}</span></div><div className="storage-list"><StorageRow icon={<Database size={17} />} label="BuildKit layers" value="—" detail="Cache inventory not reported" /><StorageRow icon={<Archive size={17} />} label="Actions cache" value="—" detail="Cache inventory not reported" /><StorageRow icon={<GitBranch size={17} />} label="Package stores" value="—" detail="Cache inventory not reported" /><StorageRow icon={<HardDrive size={17} />} label="Runner filesystem" value={host ? formatBytes(host.diskTotalBytes) : "—"} detail={host ? "total host filesystem" : "Awaiting local agent"} /></div></div></section>; }
function Metric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: ReactNode; tone?: "success" }) { return <article className="metric-card"><div className="metric-icon">{icon}</div><span className="metric-label">{label}</span><strong className={tone === "success" ? "success-text" : ""}>{value}</strong><small>{detail}</small></article>; }
function Insight({ title, detail, status, href }: { title: string; detail: string; status: string; href?: string }) { return <article className="insight-row"><div className="insight-icon"><CircleAlert size={16} /></div><div><strong>{title}</strong><span>{detail}</span></div>{href ? <a className="button button-quiet" href={href} target="_blank" rel="noreferrer">{status} <ChevronRight size={14} /></a> : <button className="button button-quiet">{status} <ChevronRight size={14} /></button>}</article>; }
function StorageRow({ icon, label, value, detail }: { icon: ReactNode; label: string; value: string; detail: string }) { return <div className="storage-row"><span className="storage-icon">{icon}</span><div><strong>{label}</strong><span>{detail}</span></div><b>{value}</b></div>; }
function EmptyState({ title, detail }: { title: string; detail: string }) { return <div className="empty-state"><strong>{title}</strong><span>{detail}</span></div>; }
